const clothesList = [
    { productName: "T-Shirt", category: "Üst Giyim", color: "Beyaz", size: "M", price: 79.99 },
    { productName: "Kot Pantolon", category: "Alt Giyim", color: "Mavi", size: "32", price: 129.99 },
    { productName: "Ceket", category: "Üst Giyim", color: "Siyah", size: "L", price: 249.99 },
    { productName: "Elbise", category: "Üst Giyim", color: "Kırmızı", size: "S", price: 199.99 },
    { productName: "Etek", category: "Alt Giyim", color: "Yeşil", size: "M", price: 89.99 },
    { productName: "Gömlek", category: "Üst Giyim", color: "Lacivert", size: "L", price: 99.99 },
    { productName: "Şort", category: "Alt Giyim", color: "Bej", size: "M", price: 59.99 },
    { productName: "Kazak", category: "Üst Giyim", color: "Gri", size: "XL", price: 149.99 },
    { productName: "Mont", category: "Dış Giyim", color: "Kahverengi", size: "L", price: 299.99 },
    { productName: "Bluz", category: "Üst Giyim", color: "Pembe", size: "M", price: 79.99 },
    { productName: "Eşofman Altı", category: "Alt Giyim", color: "Siyah", size: "L", price: 69.99 },
    { productName: "Tayt", category: "Alt Giyim", color: "Gri", size: "S", price: 49.99 },
    { productName: "Kaban", category: "Dış Giyim", color: "Bordo", size: "XL", price: 399.99 },
    { productName: "Polo T-Shirt", category: "Üst Giyim", color: "Yeşil", size: "M", price: 89.99 },
    { productName: "Kapri", category: "Alt Giyim", color: "Mavi", size: "L", price: 69.99 },
    { productName: "Sweatshirt", category: "Üst Giyim", color: "Sarı", size: "M", price: 119.99 },
    { productName: "Trençkot", category: "Dış Giyim", color: "Bej", size: "M", price: 349.99 },
    { productName: "Tunik", category: "Üst Giyim", color: "Krem", size: "S", price: 109.99 },
    { productName: "Pantolon", category: "Alt Giyim", color: "Kırmızı", size: "32", price: 139.99 },
    { productName: "Hırka", category: "Üst Giyim", color: "Mor", size: "L", price: 159.99 },
    { productName: "Atkı", category: "Aksesuar", color: "Siyah", size: "Tek Beden", price: 49.99 },
    { productName: "Şapka", category: "Aksesuar", color: "Mavi", size: "Tek Beden", price: 39.99 },
    { productName: "Eldiven", category: "Aksesuar", color: "Kırmızı", size: "Tek Beden", price: 29.99 },
    { productName: "Çorap", category: "Aksesuar", color: "Beyaz", size: "Tek Beden", price: 19.99 },
    { productName: "Kravat", category: "Aksesuar", color: "Lacivert", size: "Tek Beden", price: 79.99 },
    { productName: "Güneş Gözlüğü", category: "Aksesuar", color: "Siyah", size: "Tek Beden", price: 199.99 },
    { productName: "Spor Ayakkabı", category: "Ayakkabı", color: "Beyaz", size: "42", price: 249.99 },
    { productName: "Bot", category: "Ayakkabı", color: "Kahverengi", size: "43", price: 299.99 },
    { productName: "Topuklu Ayakkabı", category: "Ayakkabı", color: "Kırmızı", size: "38", price: 199.99 },
    { productName: "Babet", category: "Ayakkabı", color: "Bej", size: "37", price: 99.99 },
    { productName: "Sandalet", category: "Ayakkabı", color: "Siyah", size: "39", price: 79.99 },
    { productName: "Terlik", category: "Ayakkabı", color: "Mavi", size: "40", price: 49.99 },
    { productName: "Sırt Çantası", category: "Aksesuar", color: "Yeşil", size: "Tek Beden", price: 149.99 },
    { productName: "El Çantası", category: "Aksesuar", color: "Pembe", size: "Tek Beden", price: 199.99 },
    { productName: "Cüzdan", category: "Aksesuar", color: "Lacivert", size: "Tek Beden", price: 99.99 },
    { productName: "Kemer", category: "Aksesuar", color: "Siyah", size: "M", price: 49.99 },
    { productName: "Gelinlik", category: "Özel Giyim", color: "Beyaz", size: "38", price: 1499.99 },
    { productName: "Damatlık", category: "Özel Giyim", color: "Siyah", size: "52", price: 1299.99 },
    { productName: "Mezuniyet Elbisesi", category: "Özel Giyim", color: "Mavi", size: "40", price: 499.99 },
    { productName: "Abiye Elbise", category: "Özel Giyim", color: "Kırmızı", size: "36", price: 599.99 },
    { productName: "Spor Ceket", category: "Üst Giyim", color: "Gri", size: "M", price: 229.99 },
    { productName: "Yelek", category: "Üst Giyim", color: "Lacivert", size: "L", price: 189.99 },
    { productName: "Kısa Kollu Gömlek", category: "Üst Giyim", color: "Pembe", size: "M", price: 89.99 },
    { productName: "Jean Ceket", category: "Üst Giyim", color: "Mavi", size: "L", price: 199.99 },
    { productName: "Kısa Etek", category: "Alt Giyim", color: "Siyah", size: "M", price: 79.99 },
    { productName: "Maxi Etek", category: "Alt Giyim", color: "Yeşil", size: "L", price: 99.99 },
    { productName: "Palto", category: "Dış Giyim", color: "Lacivert", size: "XL", price: 449.99 },
    { productName: "Yağmurluk", category: "Dış Giyim", color: "Sarı", size: "M", price: 299.99 }
];

export default clothesList;